### ISSUE TITLE
Make chicago-brick modules into npm modules 

### ISSUE THREAD

**Issue by iatkinson** [google/chicago-brick#103]
Setting up a new chicago-brick install could be as simple as:

```
npm install --save chicago-brick 
npm install --save my-cool-brick-module
```

This would then produce a `package.json` file that describes the chicago-brick installation (yay for easy sharing).  The `package.json` file could also be expanded to include any module configuration (e.g., configure the slideshow to show specific media).

chicago-brick/module versioning can (and should) be managed using npm peer dependencies.  This also keep modules from breaking when chicago-brick introduces a major revision (breaking change).

**Comment by applmak** [comment]
One prerequisite of this (that we can maybe do now?) is to rewrite paths in modules to refer to chicago-brick libs versus other things. For example:

const ModuleInterface = require('lib/module_interface');

would become

const ModuleInterface = require('chicago_brick/lib/module_interface');

That-a-way, even in the module is moved to some weird location, we can update requirejs in the client & the node paths in the server to still find this file.

**Comment by bmt** [comment]
My plan for next steps:
- Move module definitions and default configs out of the playlist file and into a .json file in the module directory.
  - Rewrite relative client imports to /module/name/<PATH> for client serving.
  - Allow module def / config override by name in the playlist.
  - Add a disabled boolean to a module in the config.
- Add discovery of modules in node_modules directory.
- Allow modules to define third_party libraries and their requirejs config data as part of the module config.

**Comment by applmak** [comment]
This is done now, right?

**Comment by applmak** [comment]
All of this works, though we now use deno. Modules can be located wherever via the brick.json mechanism.
