### ISSUE TITLE
Clients display black screen in anything more than single client mode

### ISSUE THREAD

**Issue by zschmid** [google/chicago-brick#242]
Everything works fine if i run the server as `run_1x1.sh ` and access the client per the README at http://localhost:3000/?config=0,0,1920,1080 . 

However, if I attempt to start the chev6 or 2x2 server, and then run their respective client scripts, all i'm ever presented with is a black screen. 

Server:
`./bin/run_2x2.sh -m balls`

Client: 
`./bin/start_2x2_clients.sh`

Console output from the server shows the clients are joining successfully and the only thing that remotely looks like a potential error in the log is: `Received late request for new state from /module0X0X3840X2160X70314X600635#Bwrab8PDD9xIWiZhAAAI`

If i remove the client script from the picture and try to access one of these four windows directly from an incognito window in chrome or safari at the URL specified in the client.sh (`http://localhost:3000/?config=1,1,1,1&xscale=1920&yscale=1080`) , i also receive a black screen and nothing suspicious in the browser console. 

Do you have any insight into what might be going on? I'm at a loss for how to get everything to display for multiple screens.  I'm using all defaults on a fresh install from master. Node version locally on my Mac is v8.11.4

**Comment by zschmid** [comment]
Some more info on this. It looks like it has something to do with the dependency requirements on a fresh install in 0.4.4. I checked out tags/0.4.0 and then did an npm install there, everything worked exactly as it should in multi client mode, so it looks like there is some sort of missing dependency between 0.4.0 and master.

**Comment by plural** [comment]
hello!

A couple of things to try out.  Would you check out what module is trying to be displayed on localhost:3000/status ?

Would you also see if a more recent node makes a difference?  We are developing primarily on 10 at this point.

**Comment by applmak** [comment]
Yeah, this was totally my bad. Sorry about the breakage!
