### ISSUE TITLE
Server state machine not removing modules from module_ticker on errors

### ISSUE THREAD

**Issue by bmt** [google/chicago-brick#29]
See attached log file. This could be related to local changes -- I haven't tried in a clean client.

[walllog.txt](https://github.com/google/chicago-brick/files/125085/walllog.txt)

**Comment by applmak** [comment]
Cannot repro:

ran custom playlist with --module_duration 10:

  wall:module_state_machine Displaying  +0ms gears-fancy until 68316.34778660131
  wall:module_ticker Add: We are now ticking 2 modules: +2ms stars, gears-fancy
  wall:server_state_machine start transition +0ms 56652.33315102747
  wall:server_state_machine end transition +4s 61652.33315102747
  wall:network Closed per-module socket @ 0,0,24960,5400-45407.250683 +0ms
  wall:module_ticker Remove: We are now ticking 1 modules +1ms
  wall:state_machine ServerSM +0ms transition from TransitionState to DisplayState

**Comment by bmt** [comment]
The important condition here is a module error:
wall:server_state_machine Missing required service account key file +2ms
wall:server_state_machine Entering error state for module fulton-construction +0ms
wall:state_machine ServerSM +0ms transition from PrepareState to ErrorState

**Comment by bmt** [comment]
When a module error happens, it doesn't remove the previous module properly.  Thus modules accumulate on the server.

**Comment by applmak** [comment]
Did #24 fix this?

**Comment by applmak** [comment]
Can no longer repro.
